### ISSUE TITLE
Project status & licence

### ISSUE THREAD

**Issue by FlxPeters** [burner1024/auto-spf-flattener#2]
Hi and hello,

i really like this project and we would like to use it and contribute things like a Docker container or even a Helm chart.
The problem here is, that the project has no license referenced which makes it in fact not open source. 

So my question is: Do you still maintain this project and is there a chance to get it on a OSS license like MIT? 

For more details see: https://choosealicense.com/no-permission/

Thanks in advance,
Felix

**Comment by burner1024** [comment]
This isn't my project, I used it at some point and no longer do. It was forked from somewhere, although now github doesn't show the original, probably has been removed.
You can try contacting the people who made the commits for clarification.

**Comment by derekperkins** [comment]
@FlxPeters did you end up doing anything around this?

**Comment by FlxPeters** [comment]
No, we reorganized the domain structures to avoid SPF limits. So no need for a flattening at this time any more.
